name: Sync to Deployment Fork

on:
  push:
    branches:
      - main

jobs:
  call-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger sync in fork
        run: |
          curl -X POST https://api.github.com/repos/neue-dev/Enotaryo-Web-Client/actions/workflows/168126727/dispatches \
            -H "Authorization: token ${{ secrets.DEPLOY_FORK_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            -d '{"ref":"main"}'